[build.environment]
  NODE_VERSION = "20.18.1"
  NEXT_VERBOSE = "true"

[build]
  command = "npm --prefix ./plugins/internal-link-builder install && npm run build"
  publish = "out"
  base = "/"

[[plugins]]
  package = "./plugins/internal-link-builder"
