[build.environment]
  NODE_VERSION = "20.17.0"
  NEXT_VERBOSE = "true"
  [build]
  command = "yarn build:netlify"
  publish = "/out"
  base = "/"


[[plugins]]
  package = "./netlify/plugins/tina-fallback"
