[build.environment]
  NODE_VERSION = "20.17.0"
  NEXT_VERBOSE = "true"
  [build]

  command = "yarn tinacms build && yarn next build && yarn next build && yarn next-sitemap"
  publish = "/out"
  base = "/"



