[build.environment]
  NODE_VERSION = "20.17.0"
  NEXT_VERBOSE = "true"

[build]
  command = "npm run build"
  publish = "out"
  base = "/"

# Configure the local build plugin
[[plugins]]
  package = "./plugins/internal-link-builder"
