[build.environment]
  NODE_VERSION = "20.18.1"

[build]
  command = "npm ci && npm run build"
  publish = "out"
  base = "/"

# Enable caching of node_modules and package-lock.json
[build.processing]
  skip_processing = false

[[plugins]]
  package = "./plugins/internal-link-builder"

[build.cache]
  # Netlify automatically caches these paths
  paths = [
    "node_modules",
    "package-lock.json"
  ]
