[build.environment]
  NODE_VERSION = "20.17.0"
  NEXT_VERBOSE = "true"

[build]
  command = "npm run build"
  publish = "out"
  base = "."

[build.lifecycle]
  build_pre_script = "npm --prefix ./plugins/internal-link-builder install"

[[plugins]]
  package = "./plugins/internal-link-builder"
